# -*- coding: utf-8 -*-
"""compression_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1thhkKFGtZeII12y_jC5QxhZyjQMSfFV2
"""

from scipy.fft import dct, idct #modificaciones hechas por Jose Alberto Loaiza Nevarez


try:
    import sdsl
    SPLINE_AVAILABLE = True
except ImportError:
    SPLINE_AVAILABLE = False
# 1: Import Standard Library Modules
import math  # Mathematical functions
import os  # Operating system interfaces
import sys  # System-specific parameters and functions
import time

# 2: Import Third-Party Libraries
import numpy as np  # Numerical operations
import torch  # PyTorch for deep learning
import torch.nn as nn
import tensorflow as tf

# 3. Import core utils
from core_utils import generate_rotation_matrix_Q
from core_utils import sort_elements_with_indices
from core_utils import packbits_pytorch
from core_utils import unpackbits_pytorch
from core_utils import matrix_to_bitmap
from core_utils import bitmap_to_matrix

"""## **2.- Compression Methods**

### **2.1 Decomposition**

The main goal of this function is to **preserve the most significant values** in the matrix `D` (the larger values that contain more information) while reducing the storage requirements of the **less significant values** (the smaller ones, which are presumed to contribute less to the data's meaningful structure). To achieve this, the function first identifies and keeps the **larger values** that are outside a specified range \([l, r]\), and then **compresses the smaller values** within the range \([l, r]\) by replacing them with **segment-wise averages**.

This approach is based on the assumption that the values outside this range, where the concavity of the distribution changes, carry the most important information, while the values inside this range are less relevant and can be approximated to save memory.

**How the Decomposition Function Works**
1. **Saving the Larger Values (Preserving Important Data)**:
   - The function begins by identifying the values in `D` that lie outside the range \([l, r]\), where `l` and `r` are the **concavity change points** of the distribution of the values in `D`. These larger values, typically more informative, are preserved in the matrix `S` in their **original form**.
   
2. **Processing the Smaller Values (Memory Optimization)**:
   - The values within the range \([l, r]\), typically smaller and less important, are considered for compression. To reduce memory usage, these values are replaced with their **segment-wise averages**.
   
   - The range \([l, r]\) is divided into `num_segments` sub-ranges, and each sub-range (or segment) contains a subset of the values within the range. The function calculates the **average value** for each segment and substitutes all elements in the segment with the corresponding average. This way, the function reduces the number of distinct values in the range while maintaining the overall structure of the data.
   
**Return Values**:  
   - The function returns three things:  
     - **Matrix `S`**: Contains the values outside the range \([l, r]\), which are the larger, more significant values preserved in their original form.  
     - **Array of Averages**: An array containing the average values for each segment of the smaller values within the range \([l, r]\).  
     - **Array of Flattened Masks**: An array with flattened versions of the masks that indicate the positions of the corresponding averages within the matrix `S`. This mask can be used to locate which elements in `S` will be replaced by their segment-wise averages.  

With these return values, we can construct an approximation of `D` by obtaining a matrix for each average and mask, then adding all these new matrices to `S`, resulting in an approximation of `D`.
"""

def decomposition(D, num_bits):
    """
    Divides the range [l, r] into equal segments for both positive and negative values.
    It calculates the average of the elements within each segment, and then replaces the values
    of the elements in the range [l, r] with the corresponding segment average.
    Values outside this range are kept unchanged.

    :param D: Tensor of values (of type `torch.Tensor`) to be processed.
    :param num_bits: The number of bits for the binary matrix.

    :return:
        - S: Sparse matrix with the elements of highest absolute value
        - avg_values: List with the averages of the elements within each segment.
        - bool_masks: List of boolean masks for each segment.
    """

    dtype=torch.bfloat16

    num_segments = 2**num_bits - 1

    less_segments = num_segments // 2
    more_segments = num_segments - less_segments

    sorted_D, _ = sort_elements_with_indices(D)
    lower_limit, upper_limit = find_concavity_changes(sorted_D)

    l = sorted_D[lower_limit]
    r = sorted_D[upper_limit]

    # Filter the elements outside the range (l, r)
    mask_og = (D <= l) | (D >= r)
    S = D * mask_og.float()  # Keep values outside the range (l, r)
    non_zero_elements = S[mask_og.bool()]

    masks = []  # List to store masks
    avg_values = []  # List to store averages of negative and positive segments

    # --- Process the negative values ---
    mask_neg = (l < D) & (D < 0)  # Filter negative values
    S_neg = D * mask_neg.float()  # Only the negative values

    # --- Process the positive values ---
    mask_pos = (0 < D) & (D < r)  # Filter positive values
    S_pos = D * mask_pos.float()  # Only the positive values

    if mask_neg.sum() > mask_pos.sum():
        num_segments_l = more_segments
        num_segments_r = less_segments
    else:
        num_segments_l = less_segments
        num_segments_r = more_segments

    #print(f'num_segments_l:{num_segments_l}, num_segments_r: {num_segments_r}')

    # Divide the negative range (l, 0) into 'num_segments' segments
    neg_step = (0 - l) / num_segments_l

    for i in range(num_segments_l):
        lower = l + i * neg_step
        upper = l + (i + 1) * neg_step
        mask = (lower < D) & (D <= upper)

        # Extract and average only the elements in the segment
        segment_values = D[mask]
        avg_neg = segment_values.mean() if segment_values.numel() > 0 else torch.tensor(0.0, dtype=dtype)

        # Replace elements in D with the segment average
        S_neg[mask] = avg_neg


    # Divide the positive range (0, r) into 'num_segments' segments
    pos_step = (r - 0) / num_segments_r

    for i in range(num_segments_r):
        lower = 0 + i * pos_step
        upper = 0 + (i + 1) * pos_step
        mask = (lower < D) & (D <= upper)

        # Filter the elements in the segment
        segment_values = D[mask]
        avg_pos = segment_values.mean() if segment_values.numel() > 0 else torch.tensor(0.0, dtype=dtype)

        # Replace elements in D with the segment average
        S_pos[mask] = avg_pos

    S_segments = S_neg + S_pos
    S_segments[mask_og] = 0

    avg_values, packed_binary_matrix, og_shape_bin = compress_matrix_decomp(S_segments)

    # Return S, avg_values, and the boolean masks
    return non_zero_elements, avg_values, packed_binary_matrix, og_shape_bin

def find_concavity_changes(array, slope_threshold=1.0, atol=1e-2):
    """
    Finds the points where the slope is equal to ±45 degrees, indicating concavity changes.

    Parameters:
        array (torch.Tensor): One-dimensional (flattened) tensor.
        slope_threshold (float): Target slope value (default is 1.0 for 45 degrees).
        atol (float): Tolerance to consider a slope as equal to the target.

    Returns:
        list: Indices where the slope is approximately ±slope_threshold.
    """
    if array.dim() != 1:
        raise ValueError("The tensor must be one-dimensional (flattened).")

    downsample_factor = max(1,int(len(array)/(2**11)))

    # Calculate the necessary padding size to make the array divisible
    padding_size = (downsample_factor - len(array) % downsample_factor) % downsample_factor

    # Perform padding with zeros or replicate the last value
    if padding_size > 0:
        padding = torch.zeros(padding_size)  # Padding with zeros
        array_padded = torch.cat((array, padding))
    else:
        array_padded = array

    # Perform downsampling
    downsampled_array = array_padded.view(-1, downsample_factor).mean(dim=1)

    # Calculate dx based on the maximum value of the array
    #dx = 10**(math.floor(math.log10(torch.max(torch.abs(array)).item())) - 2)
    # Ensure the tensor is on the correct device before calling .item()
    dx = 10**(math.floor(math.log10(torch.max(torch.abs(array)).cpu().item())) - 2)

    # Compute the first derivative using vectorized finite differences
    first_derivative = (downsampled_array[1:] - downsampled_array[:-1]) / dx

    def find_indices(atol):
        condition = (
            (torch.abs(first_derivative - slope_threshold) <= atol) |
            (torch.abs(first_derivative + slope_threshold) <= atol)
        )
        return torch.nonzero(condition).squeeze(1).tolist()

    def ensure_two_elements(atol_initial, atol_max, step_size):
        atol = atol_initial
        while atol <= atol_max:
            slope_indices = find_indices(atol)
            if len(slope_indices) >= 2:
                return slope_indices
            atol += step_size  # Aumentar la tolerancia
        return slope_indices  # Devolver la mejor opción posible (aunque no haya 2)

    # Buscar índices con la tolerancia inicial
    slope_indices = ensure_two_elements(atol_initial=1e-6, atol_max=1, step_size=1e-1)

    # Si no se encuentran suficientes índices, aplicar alguna estrategia alternativa
    if len(slope_indices) < 2:
        print("Warning: Less than 2 indices found. You may need to adjust your parameters.")
        # Puedes retornar valores predeterminados o continuar con la ejecución según sea necesario

    # Ajustar los índices para que correspondan al array original (considerando downsampling)
    adjusted_indices = [i * downsample_factor for i in slope_indices]

    first_curve = adjusted_indices[0]
    second_curve = adjusted_indices[-1]


    return first_curve, second_curve

def compress_matrix_decomp(matrix):
    """Converts a matrix into unique values and a packed binary matrix."""
    unique_values, index_matrix = torch.unique(matrix, return_inverse=True)
    index_matrix = index_matrix.view(matrix.shape)

    # Calcular el número mínimo de bits necesarios
    num_bits = max(1, int(torch.ceil(torch.log2(torch.tensor(len(unique_values))))))

    # Convertir los índices a representación binaria con num_bits
    n, m = index_matrix.shape
    binary_matrix = ((index_matrix.unsqueeze(-1) >> torch.arange(num_bits - 1, -1, -1)) & 1).to(torch.int8)
    binary_matrix = binary_matrix.reshape(n, num_bits * m)

    # Empaquetar bits para reducir memoria
    packed_binary_matrix = packbits_pytorch(binary_matrix)

    return unique_values, packed_binary_matrix, binary_matrix.shape

def unpackbits_pytorch_decomp(packed, original_shape):
    """Simulates np.unpackbits using PyTorch and NumPy."""
    unpacked_numpy = np.unpackbits(packed, axis=-1)
    unpacked_numpy = unpacked_numpy[:original_shape[0],:original_shape[1]]
    unpacked_tensor = torch.from_numpy(unpacked_numpy).to(dtype=torch.bool)
    return unpacked_tensor.view(*original_shape)

def decompress_matrix_decomp(unique_values, packed_binary_matrix, original_shape):
    """Reconstructs the original matrix from unique values and the packed binary matrix."""
    # Desempaquetar bits
    binary_matrix = unpackbits_pytorch_decomp(packed_binary_matrix, original_shape)

    # Calcular el número mínimo de bits necesarios
    num_bits = max(1, (len(unique_values) - 1).bit_length())

    n, _ = binary_matrix.shape
    m = _ // num_bits
    binary_matrix = binary_matrix.view(n, m, num_bits)

    # Convertir representación binaria de vuelta a índices
    recovered_index_matrix = torch.matmul(binary_matrix.int(), torch.pow(2, torch.arange(num_bits - 1, -1, -1, device=binary_matrix.device)).int())

    # Recuperar la matriz original usando los valores únicos
    return unique_values[recovered_index_matrix]

def reconstruct_decomposition(non_zero_elements, avg_values, packed_binary_matrix, og_shape_bin):
    """
    Reconstructs a matrix from its compressed decomposition representation.
    """

    #mask = unpackbits_pytorch(packed_mask.astype(np.uint8), original_shape)

    S = decompress_matrix_decomp(avg_values, packed_binary_matrix, og_shape_bin)
    mask = (S == 0)
    non_zero_elements = non_zero_elements[:mask.sum()]
    S[mask] = non_zero_elements


    return S

"""### **2.2 Local Top K**

This is one of the methods within the proposed technique. It selects the **k** elements with the largest absolute magnitudes and sets the rest to zero. To ensure that no rows are entirely zero, it selects the **k/n** elements with the largest absolute magnitudes in each of the **n** rows.
"""

def local_topk(D, num_parameters):
    """
    Retiene los num_parameters valores más grandes en magnitud en la matriz D,
    distribuyéndolos equitativamente entre las filas.

    Parámetros:
    D (torch.Tensor): Matriz de entrada.
    num_parameters (int): Número total de valores no ceros deseados en la matriz.

    Retorna:
    torch.Tensor: Matriz modificada con solo los valores top-k por fila.
    """

    S = D.clone()
    num_rows, num_cols = D.shape

    # Calcular cuántos valores mantener por fila
    num_parameters_per_row = max(1, num_parameters // num_rows)

    # Obtener los k valores más grandes en magnitud por fila
    topk_values, _ = torch.topk(D.abs(), num_parameters_per_row, dim=1)

    # Obtener el umbral mínimo por fila para considerar un valor dentro del top-k
    min_topk_values = topk_values[:, -1].view(-1, 1)  # (num_rows, 1)

    # Crear una máscara booleana que indica qué valores mantener en cada fila
    mask = D.abs() >= min_topk_values  # (num_rows, num_cols), cada fila tiene su propia máscara

    # Aplicar la máscara a la matriz original
    S *= mask

    return S

"""### **2.3 Spline**"""

def compute_spline(D):
    if not SPLINE_AVAILABLE:
        raise NotImplementedError("Spline skipped")
    """
    Computes a spline representation of matrix D and builds a Wavelet Tree to store the permutation
    to the original order of its elements.

    Args:
        D (torch.Tensor): Input matrix.

    Returns:
        tuple:
            - spline (function): A function of the ordered elements distribution.
            - wt (bitarray): A wavelet tree representing the permutation from ordered elements back to their original order.
            - dimensions (tuple): The dimensions of matrix D.
    """
    #start_time = time.time()  # Tiempo de inicio global

    # Store the original matrix dimensions
    dimensions = D.shape

    # Sort elements and retrieve their original indices
    sorted_array, original_indices = sort_elements_with_indices(D)

    # Select representative indices based on sorted elements
    selected_indices = fractions(sorted_array)

    # Compute the spline for the sorted array
    spline, _, _ = compute_spline_with_indices(sorted_array, selected_indices)

    # Build the Wavelet Tree from the flattened matrix
    #wt = build_wavelet_tree(indices)

    original_indices = original_indices.to(dtype=torch.int32)
    wt = sdsl_python.WaveletTree(original_indices.tolist())

    # Tiempo total
    #total_time = time.time() - start_time
    #print(f"Tiempo total de compute_spline: {total_time:.4f} segundos")

    # Return the computed spline, wavelet tree, and matrix dimensions
    return spline, wt, dimensions

def compute_spline_with_indices(array, indices):
    """
    Calculates a cubic spline from a tensor and the given indices.

    Args:
        array (torch.Tensor): 1D tensor with the original values.
        indices (list or torch.Tensor): Specific indices to use for calculating the spline.

    Returns:
        CubicSpline: Cubic spline object.
        np.ndarray: Sampled original values.
    """
    if not isinstance(indices, (list, torch.Tensor)):
        raise ValueError("Indices must be a list or a tensor.")

    indices = torch.tensor(indices, dtype=torch.long)  # Ensure they are valid indices
    sampled_indices = indices.numpy()
    sampled_values = array[indices].numpy()

    # Create the cubic spline using the selected points
    spline = CubicSpline(sampled_indices, sampled_values)
    return spline, sampled_indices, sampled_values

def fractions(array, divisions=20, n_points=100):
    """
    Selects indices uniformly distributed over the first and last fractions of the array
    according to the specified number of divisions, ensuring that the start, middle, and end
    of the array are included.

    Args:
        array (torch.Tensor): 1D tensor with the original values.
        divisions (int): Number of divisions of the array (e.g., 4 for quartiles, 10 for deciles).
        n_points (int): Number of points to select (excluding start, middle, and end).

    Returns:
        list: Selected indices.
    """
    if divisions < 2:
        raise ValueError("The number of divisions must be at least 2.")
    if n_points < 1:
        raise ValueError("The number of points must be at least 1.")

    n = len(array)
    if n < divisions:
        raise ValueError(f"The size of the array must be at least {divisions}.")

    #divisions=10 #For images

    # Calculate the fraction limits
    start_end = n // divisions
    end_start = (divisions - 1) * n // divisions
    first_point = n // 100
    second_quartile = n // 2
    first_quartile = n // 4
    third_quartile = 3 * n // 4
    last_point = (100 - 1) * n // 100

    # Additional points in the fractions
    extra_points = n_points - 5  # Subtract start, quarters, middle, and end
    n_points_start = extra_points // 2
    n_points_end = extra_points - n_points_start

    # Uniformly distributed indices in the first fraction
    start_indices = torch.linspace(0, start_end - 1, n_points_start, dtype=torch.long).tolist() if n_points_start > 0 else []

    # Uniformly distributed indices in the last fraction
    end_indices = torch.linspace(end_start, n - 1, n_points_end, dtype=torch.long).tolist() if n_points_end > 0 else []

    # Ensure including start, middle, quarters, and end
    selected_indices = sorted(set([0, first_point, first_quartile, second_quartile, third_quartile, last_point, n - 1] + start_indices + end_indices))

    return selected_indices

def reconstruct_permutation(wt, n):
    """
    Recupera la secuencia original a partir del Wavelet Tree dividiendo el cálculo en 4 partes para ahorrar memoria.

    Parámetros:
    - wt: Wavelet Tree con el método access(i).
    - n: Número total de elementos en la secuencia original.

    Retorna:
    - Tensor de PyTorch con los índices en su orden original.
    """
    original_indices = torch.empty(n, dtype=torch.int32)  # Reservar memoria

    # Dividir el rango en 4 partes
    chunk_size = n // 4

    for i in range(4):
        start = i * chunk_size
        end = n if i == 3 else (i + 1) * chunk_size  # Última parte toma el resto
        original_indices[start:end] = torch.tensor(
            [wt.access(j) for j in range(start, end)], dtype=torch.int32
        )

    return original_indices

def reconstruct_spline(spline, wt, dimensions, dtype):
    """
    Reconstructs a matrix using a cubic spline approximation and a wavelet tree-based permutation.

    Parameters:
        spline (callable): A precomputed cubic spline function that maps indices to approximated values.
        wt (numpy.ndarray): A wavelet tree stored as a bit array, representing the permutation
                            that maps the sorted sequence back to the original order.
        dimensions (tuple): The original dimensions (rows, cols) of the matrix, used to reshape
                            the reconstructed values.

    Returns:
        torch.Tensor: The reconstructed matrix of shape `dimensions`, where values are estimated
                      using the cubic spline function and reordered using the wavelet tree permutation.
    """

    # Compute the total number of elements in the original matrix
    n = dimensions[0] * dimensions[1]

    # Create an array of indices from 0 to n-1
    x = torch.arange(n)

    # Recover the original order of indices using the wavelet tree
    original_indices = reconstruct_permutation(wt, n)

    # Apply the cubic spline function to obtain approximated values in sorted order
    spline_sorted_values = spline(x)

    # Rearrange the approximated values according to the original indices
    spline_values = spline_sorted_values[torch.argsort(original_indices)]

    # Reshape the values into the original matrix dimensions
    D = spline_values.reshape(dimensions)

    # Convert the NumPy array to a PyTorch tensor
    D = torch.Tensor(D)

    return D.to(dtype=dtype)

"""### **2.4 Low Rank**"""

def low_rank_approximation(matrix, num_parameters):
    """
    Computes a low-rank approximation of the given matrix using its SVD decomposition
    and a specified number of parameters (rank `r`).

    Args:
        matrix (torch.Tensor): The input matrix to be approximated.
        num_parameters (int): The desired number of parameters to retain in the approximation.

    Returns:
        torch.Tensor: The truncated left singular vectors multiplied by the truncated singular values (product of U_r and S_r_matrix).
        torch.Tensor: The truncated right singular vectors matrix (Vt_r).
    """
    # Perform Singular Value Decomposition (SVD) on the matrix
    # Perform Singular Value Decomposition (SVD) on the matrix
    orig_dtype = matrix.dtype
    matrix = matrix.to(torch.float32)
    U, S, Vt = torch.linalg.svd(matrix, full_matrices=False)
    U, S, Vt = U.to(orig_dtype), S.to(orig_dtype), Vt.to(orig_dtype)

    # Get the shape of the matrix
    m, n = matrix.shape

    # Calculate the rank `r` using the formula: num_parameters = r * (m + n)
    r = num_parameters // (m + n)  # Rank `r` is computed based on the desired number of parameters

    # Truncate U, S, Vt based on the computed rank `r`
    U_r = U[:, :r]  # Keep the first `r` columns of U (left singular vectors)
    S_r = S[:r]     # Keep the first `r` singular values
    Vt_r = Vt[:r, :]  # Keep the first `r` rows of Vt (right singular vectors)

    # Create a diagonal matrix from the first `r` singular values
    S_r_matrix = torch.zeros(r, r, dtype=U_r.dtype, device=U_r.device)
    S_r_matrix = torch.diag(S_r)  # Fill the diagonal with the singular values

    # Multiply U_r with the diagonal matrix of singular values to get one matrix
    US_r = U_r @ S_r_matrix

    return US_r, Vt_r

"""### **2.5 JPEG**"""

# Matriz de cuantización estándar (JPEG Quality = 50)
Q50 = np.array([
    [16, 11, 10, 16, 24, 40, 51, 61],
    [12, 12, 14, 19, 26, 58, 60, 55],
    [14, 13, 16, 24, 40, 57, 69, 56],
    [14, 17, 22, 29, 51, 87, 80, 62],
    [18, 22, 37, 56, 68, 109, 103, 77],
    [24, 35, 55, 64, 81, 104, 113, 92],
    [49, 64, 78, 87, 103, 121, 120, 101],
    [72, 92, 95, 98, 112, 100, 103, 99]
], dtype=np.float32)

# Funciones DCT e IDCT 2D
def dct2d(block):
    return dct(dct(block.T, norm='ortho').T, norm='ortho')

def idct2d(block):
    return idct(idct(block.T, norm='ortho').T, norm='ortho')

# Orden Zigzag
def zigzag_order(block):
    index_order = np.array([
        [0,  1,  5,  6, 14, 15, 27, 28],
        [2,  4,  7, 13, 16, 26, 29, 42],
        [3,  8, 12, 17, 25, 30, 41, 43],
        [9, 11, 18, 24, 31, 40, 44, 53],
        [10, 19, 23, 32, 39, 45, 52, 54],
        [20, 22, 33, 38, 46, 51, 55, 60],
        [21, 34, 37, 47, 50, 56, 59, 61],
        [35, 36, 48, 49, 57, 58, 62, 63]
    ])
    return block.flatten()[index_order.flatten()]

def inverse_zigzag(flattened, h, w):
    index_order = zigzag_order(np.arange(h * w).reshape(h, w)).reshape(h, w)
    block = np.zeros((h, w), dtype=np.float32)
    block.flat[index_order] = flattened
    return block

# Run-Length Encoding (RLE)
def run_length_encoding(data):
    encoded = []
    count = 1
    for i in range(1, len(data)):
        if data[i] == data[i - 1]:
            count += 1
        else:
            encoded.append((data[i - 1], count))
            count = 1
    encoded.append((data[-1], count))
    return encoded

def run_length_decoding(encoded):
    return np.array([val for val, count in encoded for _ in range(int(count))])

# Huffman Encoding
class HuffmanNode:
    def __init__(self, symbol, freq):
        self.symbol = symbol
        self.freq = freq
        self.left = None
        self.right = None

    def __lt__(self, other):
        return self.freq < other.freq

def build_huffman_tree(data):
    freq = Counter(data)
    heap = [HuffmanNode(symbol, f) for symbol, f in freq.items()]
    heapq.heapify(heap)

    while len(heap) > 1:
        left = heapq.heappop(heap)
        right = heapq.heappop(heap)
        new_node = HuffmanNode(None, left.freq + right.freq)
        new_node.left = left
        new_node.right = right
        heapq.heappush(heap, new_node)

    return heap[0]

def generate_huffman_codes(node, prefix="", codebook={}):
    if node:
        if node.symbol is not None:
            codebook[node.symbol] = prefix
        generate_huffman_codes(node.left, prefix + "0", codebook)
        generate_huffman_codes(node.right, prefix + "1", codebook)
    return codebook

def huffman_encode(data):
    tree = build_huffman_tree(data)
    codebook = generate_huffman_codes(tree)

    # Convertir la cadena binaria a una lista de enteros (0s y 1s)
    bit_list = [int(bit) for symbol in data for bit in codebook[symbol]]

    # Convertir la lista de bits a un BitVector
    bit_vector = sdsl_python.BitVector(bit_list)

    return bit_vector, tree

def huffman_decode(bit_vector, tree):
    # Convertir el BitVector de vuelta a una lista de 0s y 1s
    bit_list = bit_vector.to_vector()

    decoded = []
    node = tree
    for bit in bit_list:
        node = node.left if bit == 0 else node.right
        if node.symbol is not None:
            decoded.append(node.symbol)
            node = tree

    return np.array(decoded)

# Función para comprimir imagen
def pad_image(A):
    """Añade padding a la imagen para que sus dimensiones sean múltiplos de 8."""
    h, w = A.shape
    pad_h = (8 - (h % 8)) % 8
    pad_w = (8 - (w % 8)) % 8

    A_padded = np.pad(A, ((0, pad_h), (0, pad_w)), mode='constant', constant_values=0)

    return A_padded, (h, w)  # Retorna la imagen con padding y el tamaño original

def compress_jpeg(A, quality=50):
    A = A.detach().float().numpy()
    A, original_shape = pad_image(A)  # Aplicar padding
    #start_time = time.time()
    h, w = A.shape
    compressed = []

    Q = Q50 * (50 / quality)  # Ajuste de cuantización

    for i in range(0, h, 8):
        for j in range(0, w, 8):
            block = A[i:i+8, j:j+8]
            D = dct2d(block)
            Dq = np.round(D / Q)
            zigzagged = zigzag_order(Dq)
            rle_encoded = run_length_encoding(zigzagged)
            compressed.extend(rle_encoded)

    huffman_encoded, huff_tree = huffman_encode(compressed)

    #total_compress_time = time.time() - start_time
    #print(f'Tiempo total de compresión: {total_compress_time:.6f}s')

    return huffman_encoded, huff_tree, original_shape, Q


# Función para descomprimir imagen optimizada (parcialmente vectorizada)
def remove_padding(A_padded, original_shape):
    """Elimina el padding de la imagen y la devuelve a su tamaño original."""
    h, w = original_shape
    return A_padded[:h, :w]

def decompress_jpeg(huffman_encoded, huff_tree, original_shape, Q):
    #start_time = time.time()

    h_padded = (original_shape[0] + 7) // 8 * 8  # Redondeo al múltiplo de 8 más cercano
    w_padded = (original_shape[1] + 7) // 8 * 8

    decompressed = np.zeros((h_padded, w_padded), dtype=np.float32)

    decoded_rle = huffman_decode(huffman_encoded, huff_tree)
    decoded_data = run_length_decoding(decoded_rle)

    index = 0
    for i in range(0, h_padded, 8):
        for j in range(0, w_padded, 8):
            zigzagged = decoded_data[index:index + 64]
            Dq = inverse_zigzag(zigzagged, 8, 8)
            D = Dq * Q
            decompressed[i:i+8, j:j+8] = idct2d(D)
            index += 64

    decompressed = remove_padding(decompressed, original_shape)  # Quitar padding

    #total_decompress_time = time.time() - start_time
    #print(f'Tiempo total de descompresión: {total_decompress_time:.6f}s')

    return torch.Tensor(decompressed)

"""### **2.6 DCT**"""

def global_topk(D, percentage=50):
    """
    Selecciona los coeficientes con mayor magnitud en valor absoluto, manteniendo un porcentaje específico,
    utilizando la función topk de PyTorch.

    Parámetros:
    - D: Bloque de coeficientes DCT (como un arreglo de numpy o tensor de PyTorch).
    - percentage: Porcentaje de coeficientes a conservar (0-100).

    Retorna:
    - Bloque de coeficientes DCT con el porcentaje especificado de los coeficientes originales.
    """
    # Convertir D a un tensor de PyTorch si no lo es
    D_tensor = torch.tensor(D)

    # Obtener el número total de coeficientes en el bloque DCT
    total_coefficients = D_tensor.numel()
    num_coefficients_to_keep = int((percentage / 100) * total_coefficients)

    # Obtener los coeficientes más grandes en magnitud usando topk
    values, indices = torch.topk(torch.abs(D_tensor).flatten(), num_coefficients_to_keep)

    # Crear un tensor de ceros del mismo tamaño que D
    compressed_D = torch.zeros_like(D_tensor)

    # Colocar los coeficientes seleccionados en el tensor de salida
    compressed_D.flatten()[indices] = D_tensor.flatten()[indices]

    # Convertir de nuevo a numpy si D era numpy
    return compressed_D

# Función que utiliza la DCT de scipy y regresa el resultado como un tensor de PyTorch
def dct_pytorch(input_tensor, type=2, norm='ortho'):
    # Convertir input_tensor a tensor de PyTorch si es un ndarray de NumPy
    if isinstance(input_tensor, np.ndarray):
        input_tensor = torch.tensor(input_tensor, dtype=torch.float32)

    # Asegurarse de que el tensor esté en CPU antes de convertirlo a numpy
    input_tensor_cpu = input_tensor.cpu().numpy()

    # Realizar la DCT usando scipy
    result_dct = dct(dct(input_tensor_cpu.T, norm='ortho').T, norm='ortho')

    # Convertir el resultado nuevamente a tensor de PyTorch y mantener el dtype
    result_tensor = torch.tensor(result_dct, dtype=input_tensor.dtype, device=input_tensor.device)

    return result_tensor

# Función inversa usando IDCT de SciPy y regresando el tensor en PyTorch
def idct_pytorch(input_tensor, type=2, norm='ortho'):

    input_tensor = torch.tensor(input_tensor, dtype=torch.float32)

    # Asegurarse de que el tensor esté en CPU y como un tipo adecuado para SciPy
    input_tensor_cpu = input_tensor.cpu().numpy()

    # Realizar la IDCT usando scipy
    result_idct = idct(idct(input_tensor_cpu.T, norm='ortho').T, norm='ortho')

    # Convertir el resultado nuevamente a tensor de PyTorch y mantener el dtype
    result_tensor = torch.tensor(result_idct, dtype=input_tensor.dtype, device=input_tensor.device)

    return result_tensor

def pad_image_pytorch(A):
    # Asegúrate de que la imagen tenga un tamaño adecuado para la división en bloques
    h, w = A.shape
    pad_h = (8 - (h % 8)) % 8
    pad_w = (8 - (w % 8)) % 8

    A_padded = torch.cat([A, torch.zeros((h, pad_w), dtype=A.dtype)], dim=1)  # Rellenar las columnas
    A_padded = torch.cat([A_padded, torch.zeros((pad_h, A_padded.shape[1]), dtype=A.dtype)], dim=0)  # Rellenar las filas

    return A_padded, (h, w)  # Retorna la imagen con padding y las dimensiones originales

def remove_padding_pytorch(A_padded, og_shape):
    h, w = og_shape
    return A_padded[:h, :w]  # Elimina el padding, devolviendo la forma original

def compress_dct(A, og_dtype=None, percentage=20):
    if og_dtype is None:
        og_dtype = A.dtype if isinstance(A, torch.Tensor) else torch.float16
    start_time = time.time()  # Tiempo de inicio

    # Asegúrate de que A sea un tensor de PyTorch y comprobar el tipo
    A = torch.tensor(A, dtype=torch.float32)
    A, og_shape = pad_image_pytorch(A)  # Agregar relleno a la imagen

    h, w = A.shape
    # Dividir la imagen en bloques de 8x8
    blocks = A.reshape(h // 8, 8, w // 8, 8)  # Dividir en bloques de 8x8

    # Aplicar DCT a cada bloque
    blocks_dct = torch.stack([dct_pytorch(block) for block in blocks.reshape(-1, 8, 8)])

    # Aplicar global_topk a todos los bloques de una vez
    blocks_compressed = torch.stack([global_topk(D, percentage).to(dtype=og_dtype) for D in blocks_dct])

    # Volver a la forma de la matriz original y aplicar matrix_to_bitmap a cada bloque
    compressed = blocks_compressed.reshape(h, w)  # Volver a una sola matriz h, w

    non_zero_elements, packed_mask, bitmap_shape = matrix_to_bitmap(compressed, og_dtype)

    return non_zero_elements, packed_mask, bitmap_shape, (h, w), og_shape  # Retorna la imagen comprimida y su forma


def decompress_dct(non_zero_elements, packed_mask, bitmap_shape, shape, og_shape):
    h, w = shape  # Dimensiones de la imagen

    # Descomprimir la matriz a partir de los elementos no cero y la máscara
    decompressed = bitmap_to_matrix(non_zero_elements, packed_mask, bitmap_shape)

    decompressed = decompressed.reshape(h // 8, 8, w // 8, 8)

    blocks_idct = torch.stack([idct_pytorch(block) for block in decompressed.reshape(-1, 8, 8)])

    # Ahora decompressed debería tener las dimensiones (h, w), que es lo que necesitamos para la imagen final
    decompressed_image = blocks_idct.reshape(h, w)  # Asegurar la forma correcta

    # Eliminar el relleno de la imagen
    decompressed_image = remove_padding_pytorch(decompressed_image, og_shape)

    return decompressed_image

"""### **2.7 Efficient DCT**"""

def compress_edct(A, og_dtype=None, percentage=25):
    if og_dtype is None:
        og_dtype = A.dtype if isinstance(A, torch.Tensor) else torch.float16
    A = A.numpy()
    blocksize = math.gcd(*A.shape)

    h, w = A.shape
    compressed_blocks = []

    for i in range(0, h, blocksize):
        for j in range(0, w, blocksize):
            block = A[i:min(i+blocksize, h), j:min(j+blocksize, w)]
            D = dct2d(block)

            # Calcular el tamaño de la submatriz cuadrada
            num_elements = D.shape[0] * D.shape[1]
            k = int(np.floor(np.sqrt(num_elements * percentage / 100)))

            k = min(k, D.shape[0], D.shape[1])  # Asegurar que no se pase del tamaño del bloque

            Ds = D[:k, :k]  # Extraer la submatriz superior izquierda
            Ds = torch.Tensor(Ds)
            Ds = Ds.to(og_dtype)

            compressed_blocks.append(Ds)  # Guardar también el tamaño original del bloque

    return compressed_blocks, (h, w)  # Retorna la imagen comprimida y su forma

def decompress_edct(compressed_blocks, shape):
    h, w = shape
    blocksize = math.gcd(*shape)
    decompressed = np.zeros((h, w), dtype=np.float32)

    index = 0
    for i in range(0, h, blocksize):
        for j in range(0, w, blocksize):
            block = decompressed[i:min(i+blocksize, h), j:min(j+blocksize, w)]
            block_shape = block.shape

            D_small = compressed_blocks[index]
            D_small = D_small.to(torch.float32).numpy()

            k = D_small.shape[0]

            # Reconstruir la matriz con padding de ceros del tamaño correcto
            D = np.zeros(block_shape, dtype=np.float32)
            D[:k, :k] = D_small

            # Asegurarse de no escribir fuera de los límites
            decompressed[i:i+block_shape[0], j:j+block_shape[1]] = idct2d(D)
            index += 1

    return torch.Tensor(decompressed)

########################################### FLAG
print("Program finished")
input("Press Enter to exit...")