# -*- coding: utf-8 -*-
"""core_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZU8f3s5PR7eNPFJDMjppFtMhJhdJMhkU
"""

# 1: Import Standard Library Modules
import math  # Mathematical functions
import os  # Operating system interfaces
import sys  # System-specific parameters and functions
import time

# 2: Import Third-Party Libraries
import numpy as np  # Numerical operations
import torch  # PyTorch for deep learning
import torch.nn as nn
import tensorflow as tf

"""## **1.- Core Utils**

### **1.1 Generation of common factor matrix**

A rotation matrix **Q** is generated using the following methodology:  

1. Generate a random matrix.  
2. Perform the QR decomposition of this matrix.  
3. Take the **Q** matrix obtained from the QR decomposition.  
4. Ensure that **Q** is a rotation matrix by verifying that:  
   + Its determinant is equal to 1.
"""

def generate_rotation_matrix_Q(n, dtype=torch.bfloat16):
    """
    Generates an n x n rotation matrix Q using TensorFlow and returns it as a PyTorch tensor.

    The columns of Q are orthonormal vectors, and the matrix has a determinant of 1.

    Args:
        n (int): Size of the matrix.
        dtype (torch.dtype): Desired dtype for the output rotation matrix (e.g., torch.float32, torch.float16).

    Returns:
        torch.Tensor: Orthonormal rotation matrix Q as a PyTorch tensor.
    """

    # Generate a random matrix in TensorFlow
    random_matrix = tf.random.normal(shape=(n, n), mean=0.0, stddev=1.0)

    # Apply QR decomposition to obtain an orthonormal matrix Q in TensorFlow
    Q, R = tf.linalg.qr(random_matrix)

    # Ensure that Q is a rotation matrix (det(Q) = 1)
    det_Q = tf.linalg.det(Q)
    if tf.math.less(det_Q, 0):
        # Adjust the sign of the last column to ensure det(Q) = 1
        Q = tf.concat([Q[:, :-1], -Q[:, -1:]], axis=1)  # Multiply the last column by -1

    # Convert Q from TensorFlow to a PyTorch tensor
    Q_torch = torch.tensor(Q.numpy(), dtype=dtype)

    return Q_torch

"""### **1.2 Sort elements**"""

def sort_elements_with_indices(D):
    """
    Sorts a tensor and returns the sorted tensor along with the indices
    to reconstruct the original order.

    Args:
        D (torch.Tensor): Tensor to be sorted.

    Returns:
        torch.Tensor: Sorted tensor.
        torch.Tensor: Permutation indices.
    """
    # Flatten the tensor
    flattened_array = D.flatten()

    # Sort the elements and get the indices
    sorted_array, indices = torch.sort(flattened_array)

    return sorted_array, indices

"""### **1.3 Compress bit tensors**"""

def packbits_pytorch(tensor):
    """Simula np.packbits en PyTorch utilizando np.packbits"""
    # Convertir el tensor de PyTorch a un array de Numpy
    tensor_numpy = tensor.numpy()

    # Usamos np.packbits para realizar la conversión
    packed = np.packbits(tensor_numpy, axis=-1)  # Convertir de bits a bytes

    # Regresar el resultado como tensor de PyTorch
    return packed


def unpackbits_pytorch(packed, original_shape):
    """Simula np.unpackbits en PyTorch utilizando np.unpackbits"""

    # Usamos np.unpackbits para convertir los bytes a bits
    unpacked_numpy = np.unpackbits(packed, axis=-1)

    # Regresar el resultado como tensor de PyTorch
    unpacked_tensor = torch.from_numpy(unpacked_numpy).to(dtype=torch.bool)

    # Redimensionar a la forma original deseada
    return unpacked_tensor.view(*original_shape)

"""### **1.4 Matrix to Bitmap**"""

def matrix_to_bitmap(matrix, dtype):
    """
    Converts a sparse matrix (PyTorch tensor) to its bitmap representation.

    Parameters:
        matrix (torch.Tensor): Original matrix, not necessarily binary.

    Returns:
        bit_array (bit vector): Flattened bit array representing the matrix mask.
        non_zero_elements (torch.Tensor): Tensor containing the non-zero elements of the matrix.
        dimensions (tuple): Original dimensions of the matrix.
    """
    # Step 1: Store the matrix dimensions
    original_shape = matrix.shape

    if isinstance(matrix, torch.Tensor):
        # Step 2: Create the binary mask (1 if the element is non-zero, 0 otherwise)
        mask = (matrix != 0).byte()  # Convert to byte tensor
        # Step 3: Extract the non-zero elements
        non_zero_elements = matrix[mask.bool()]
        # Step 4: Pack bits
        packed_mask = packbits_pytorch(mask)

        # Return the objects
        return non_zero_elements.to(dtype=dtype), packed_mask, original_shape

    else:
        # Step 2: Create the binary mask (1 if the element is non-zero, 0 otherwise)
        mask = (matrix != 0).astype(np.uint8)  # Convert to uint8 numpy array
        # Step 3: Extract the non-zero elements
        non_zero_elements = matrix[mask.astype(bool)]
        # Step 4: Pack bits
        packed_mask = np.packbits(mask)

        return non_zero_elements, packed_mask, original_shape

def bitmap_to_matrix(non_zero_elements, packed_mask, original_shape):
    """
    Reconstructs the original matrix from its bitmap representation using bitarray.

    Parameters:
        non_zero_elements (torch.Tensor or np.ndarray): The tensor containing the non-zero elements of the matrix.
        packed_mask (bytes): Packed bitmask representing the matrix.
        original_shape (tuple): The original dimensions of the matrix.

    Returns:
        torch.Tensor or np.ndarray: The reconstructed matrix.
    """
    # Paso 1: Convertir la matriz de bits a tensor booleano o arreglo booleano
    if isinstance(packed_mask, torch.Tensor):
        # Si packed_mask es un tensor de PyTorch, utilizamos unpackbits de PyTorch
        mask = unpackbits_pytorch(packed_mask, original_shape)
    else:
        # Si packed_mask es un arreglo de NumPy, utilizamos unpackbits de NumPy
        mask = np.unpackbits(packed_mask).astype(np.bool_)
        mask = mask[:np.prod(original_shape)].reshape(original_shape)

    # Paso 2: Crear la matriz vacía y restaurar los valores no nulos
    if isinstance(non_zero_elements, torch.Tensor):
        # Si los elementos no nulos son un tensor de PyTorch, usamos torch.zeros
        reconstructed_matrix = torch.zeros(original_shape, dtype=non_zero_elements.dtype, device=non_zero_elements.device)
    else:
        # Si los elementos no nulos son un arreglo de NumPy, usamos np.zeros
        reconstructed_matrix = np.zeros(original_shape, dtype=non_zero_elements.dtype)

    # Paso 3: Rellenar la matriz reconstruida con los elementos no nulos
    reconstructed_matrix[mask] = non_zero_elements

    return reconstructed_matrix
############################# FLAG
print("Program finished")
input("Press Enter to exit...")