# -*- coding: utf-8 -*-
"""model_compression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7yVlEjyy6EGzw82IBZDeyi96jezuS9e
"""
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # TF uses CPU, PyTorch keeps GPU
# 1: Import Standard Library Modules
import math  # Mathematical functions
import os  # Operating system interfaces
import sys  # System-specific parameters and functions
import time

# 2: Import Third-Party Libraries
import numpy as np  # Numerical operations
import torch  # PyTorch for deep learning
import torch.nn as nn
import tensorflow as tf
import psutil  # Para obtener información del sistema
import threading
import multiprocessing
from concurrent.futures import ThreadPoolExecutor

# 3. Import core utils
from core_utils import generate_rotation_matrix_Q
from core_utils import sort_elements_with_indices
from core_utils import packbits_pytorch
from core_utils import unpackbits_pytorch
from core_utils import matrix_to_bitmap
from core_utils import bitmap_to_matrix

# 4. Import compression methods
from compression_methods import decomposition, find_concavity_changes, compress_matrix_decomp, unpackbits_pytorch_decomp, decompress_matrix_decomp, reconstruct_decomposition
from compression_methods import local_topk, global_topk
from compression_methods import compute_spline, compute_spline_with_indices, fractions, reconstruct_permutation, reconstruct_spline
from compression_methods import low_rank_approximation
from compression_methods import compress_jpeg, decompress_jpeg, dct2d, idct2d, zigzag_order, inverse_zigzag, run_length_encoding, run_length_decoding, HuffmanNode, build_huffman_tree, generate_huffman_codes, huffman_encode, huffman_decode, pad_image, remove_padding
from compression_methods import dct_pytorch, idct_pytorch, pad_image_pytorch, remove_padding_pytorch, compress_dct, decompress_dct
from compression_methods import compress_edct, decompress_edct

"""## **2.- Functions for Compression of Lineal Layers**

### **2.1 Compute memory reduction of state_dict**
"""

# Función para calcular el tamaño en bytes de un objeto (tensor, BitVector, numpy array, etc.)
def get_size_in_bytes(obj):
    if isinstance(obj, torch.Tensor):
        return obj.element_size() * obj.numel()
    elif isinstance(obj, np.ndarray):
        return obj.nbytes
    elif isinstance(obj, list) or isinstance(obj, tuple):
        # Si el objeto es una lista, recorrerla y sumar el tamaño de sus elementos
        return sum(get_size_in_bytes(item) for item in obj)
    elif isinstance(obj, dict):
        # Si el objeto es un diccionario, recorrerlo y sumar el tamaño de sus claves y valores
        return sum(get_size_in_bytes(k) + get_size_in_bytes(v) for k, v in obj.items())
    else:
        # En caso de encontrar otro tipo de objeto, devolvemos su tamaño en bytes utilizando sys.getsizeof
        return sys.getsizeof(obj)

# Función para calcular el tamaño de los diccionarios y la reducción de tamaño
def compute_memory_reduction(state_dict, compressed_state_dict):
    # Inicializa el tamaño total para state_dict
    total_size_bytes_state = 0

    #print("\nMemory breakdown for state_dict:")
    for key, tensor in state_dict.items():
        tensor_size = tensor.element_size() * tensor.numel()
        total_size_bytes_state += tensor_size
        #print(f"  {key}: {tensor_size} bytes")

    original_size = total_size_bytes_state
    original_size_gb = original_size / 1e9
    original_size_mb = original_size / 1e6
    print(f"\nTotal memory size of state_dict: {original_size} bytes ({original_size_mb:.2f} MB, {original_size_gb:.6f} GB)")

    # Inicializa el tamaño total para compressed_state_dict
    total_size_bytes_compressed = 0

    #print("\nMemory breakdown for compressed_state_dict:")
    for key, value in compressed_state_dict.items():
        #print(f"Processing {key}...")

        if isinstance(value, dict):
            for subkey, subvalue in value.items():
                subvalue_size = get_size_in_bytes(subvalue)
                total_size_bytes_compressed += subvalue_size
                #print(f"  Subkey: {subkey} - Size: {subvalue_size} bytes")
        else:
            value_size = get_size_in_bytes(value)
            total_size_bytes_compressed += value_size
            #print(f"  Direct value - Size: {value_size} bytes")

    compressed_size = total_size_bytes_compressed
    compressed_size_gb = compressed_size / 1e9
    compressed_size_mb = compressed_size / 1e6
    print(f"\nTotal memory size of compressed_state_dict: {compressed_size} bytes ({compressed_size_mb:.2f} MB, {compressed_size_gb:.6f} GB)")

    # Calcular la reducción de tamaño
    reduction_percentage = 100 * (original_size - compressed_size) / original_size
    print(f"\nReducción en tamaño: {reduction_percentage:.2f}%\n")

"""### **2.2 Compute rotation Matrices dict for model**"""

def collect_column_dimensions(weights):
    """
    Extrae las dimensiones de las columnas de todas las matrices de pesos y las almacena en un conjunto.

    Parameters:
        weights (dict): Un diccionario donde las claves son los nombres de las capas y los valores son los tensores de los pesos.

    Returns:
        column_dimensions (set): Un conjunto con las dimensiones de las columnas de las matrices de pesos.
    """
    column_dimensions = set()  # Usamos un set para evitar duplicados

    for key, weight in weights.items():
        if weight.ndimension() == 2:  # Solo matrices 2D
            _, num_columns = weight.shape  # Obtiene el número de columnas
            column_dimensions.add(num_columns)  # Agrega al conjunto

            dtype = weight.dtype

    return column_dimensions, dtype

def compute_rotation_matrices_of_weights(weights):
    """
    Aplica una matriz de rotación Q a cada capa del modelo cuya dimensión de columnas se encuentra en el conjunto.

    Parameters:
        weights (dict): Un diccionario donde las claves son los nombres de las capas y los valores son los tensores de los pesos.

    Returns:
        rotation_matrices (dict): Diccionario de matrices de rotación, donde la clave es la dimensión de las columnas.
    """
    # Paso 1: Extraer las dimensiones de las columnas
    column_dimensions, dtype = collect_column_dimensions(weights)

    # Paso 2: Crear la matriz de rotación para cada dimensión
    rotation_matrices = {}

    for n in column_dimensions:
        #Q = generate_rotation_matrix_Q(n, dtype)
        Q = generate_rotation_matrix_Q(n)
        rotation_matrices[n] = Q  # Almacena la matriz de rotación para cada dimensión

    return rotation_matrices

"""### **2.3 Compress model matrices with any method**"""

def compress_model_matrices(model, weights, method, rotation_matrices=None, num_bits=4):

    if (method not in ['LRA', 'JPEG', 'DCT', 'EDCT']) and (rotation_matrices is None):
        rotation_matrices = compute_rotation_matrices_of_weights(weights)

    compressed_state_dict = {}

    for key, weight in weights.items():
        og_dtype = weight.dtype

        # Verificar si el tensor pertenece a una capa Linear
        is_linear_layer = any(key.startswith(name) and isinstance(layer, torch.nn.Linear)
                              for name, layer in model.named_modules())

        # Solo comprimir si es una matriz 2D, pertenece a una capa Linear y tiene "layer" en el nombre
        if weight.ndimension() == 2 and "layer" in key and is_linear_layer:
            matrix_start_time = time.perf_counter()

            matrix = weight

            num_parameters = matrix.shape[0] * matrix.shape[1] // 2

            if method == 'LRA':
                US_r, Vt_r = low_rank_approximation(matrix, num_parameters)
                compressed_state_dict[key] = {
                    'US_r': US_r.to(dtype=og_dtype),
                    'Vt_r': Vt_r.to(dtype=og_dtype)}
                rotation_matrices = None

            elif method == 'JPEG':
                huffman_encoded, huff_tree, shape, Q = compress_jpeg(matrix)
                compressed_state_dict[key] = {
                    'huffman_encoded': huffman_encoded,
                    'huff_tree': huff_tree,
                    'shape': shape,
                    'Q': Q}
                rotation_matrices = None

            elif method == 'DCT':
                compressed, shape, og_shape = compress_dct(matrix)
                compressed_state_dict[key] = {
                    'compressed': compressed,
                    'shape': shape,
                    'og_shape': og_shape}
                rotation_matrices = None

            elif method == 'EDCT':
                Ds, shape = compress_edct(matrix)
                compressed_state_dict[key] = {
                    'Ds': Ds,
                    'shape': shape}
                rotation_matrices = None

            elif method == 'LocalTopK':
                Q = rotation_matrices[matrix.shape[1]].to(dtype=matrix.dtype)
                D = torch.matmul(matrix, Q.T)
                S = local_topk(D, num_parameters)
                non_zero_elements, packed_mask, dimensions = matrix_to_bitmap(S, og_dtype)

                compressed_state_dict[key] = {
                    'packed_mask': packed_mask,
                    'non_zero_elements': non_zero_elements,
                    'dimensions': dimensions,
                }

            elif method == 'Decomp':
                Q = rotation_matrices[matrix.shape[1]].to(dtype=matrix.dtype)
                D = torch.matmul(matrix, Q.T)
                #S, avg_values, packed_binary_matrix, og_shape_bin = decomposition(D, num_bits)
                #non_zero_elements, packed_mask, dimensions = matrix_to_bitmap(S, og_dtype)
                # compressed_state_dict[key] = {
                #     'packed_mask': packed_mask,
                #     'non_zero_elements': non_zero_elements,
                #     'dimensions': dimensions,
                #     'avg_values': avg_values,
                #     'packed_binary_matrix': packed_binary_matrix,
                #     'og_shape_bin': og_shape_bin
                # }
                dimensions = D.shape
                non_zero_elements, avg_values, packed_binary_matrix, og_shape_bin = decomposition(D, num_bits)
                compressed_state_dict[key] = {
                    'non_zero_elements': non_zero_elements,
                    'dimensions': dimensions,
                    'avg_values': avg_values,
                    'packed_binary_matrix': packed_binary_matrix,
                    'og_shape_bin': og_shape_bin
                }

            elif method == 'Spline':
                Q = rotation_matrices[matrix.shape[1]].to(dtype=matrix.dtype)
                D = torch.matmul(matrix, Q.T)
                spline, wt, dimensions = compute_spline(D)
                compressed_state_dict[key] = {
                    'spline': spline,
                    'wt': wt,
                    'dimensions': dimensions}
        else:
            # Para tensores que no cumplen los requisitos, se almacenan sin cambios
            compressed_state_dict[key] = weight

    # Agregar rotation_matrices al diccionario final
    compressed_state_dict['rotation_matrices'] = rotation_matrices

    return compressed_state_dict

"""### **2.4 Decompressed matrix**"""

def decompress_matrix(compressed_data, method, rotation_matrix=None, gpu=None):
    """
    Decompresses a single matrix from its compressed representation.

    Parameters:
        compressed_data (dict): The compressed representation of the matrix.
        method (str): The compression method used ('LRA', 'LocalTopK', 'Decomp', 'Spline').
        rotation_matrix (torch.Tensor, optional): The rotation matrix used during compression (if applicable).
    Returns:
        torch.Tensor: The decompressed matrix.
    """

    start_time = time.perf_counter()

    if method == 'LRA':
        US_r = compressed_data['US_r']
        Vt_r = compressed_data['Vt_r']

        if gpu is None:
            US_r = US_r.to(dtype=torch.float32)
            Vt_r = Vt_r.to(dtype=torch.float32)

        result = torch.matmul(US_r, Vt_r)

    elif method == 'JPEG':
        huffman_encoded = compressed_data['huffman_encoded']
        huff_tree = compressed_data['huff_tree']
        shape = compressed_data['shape']
        Q = compressed_data['Q']

        result = decompress_jpeg(huffman_encoded, huff_tree, shape, Q)

    elif method == 'DCT':
        compressed = compressed_data['compressed']
        shape = compressed_data['shape']
        og_shape = compressed_data['og_shape']

        result = decompress_dct(compressed, shape, og_shape)

    elif method == 'EDCT':
        Ds = compressed_data['Ds']
        shape = compressed_data['shape']

        result = decompress_edct(Ds, shape)

    elif method == 'LocalTopK':
        packed_mask = compressed_data['packed_mask']
        non_zero_elements = compressed_data['non_zero_elements']
        dimensions = compressed_data['dimensions']

        S = bitmap_to_matrix(non_zero_elements, packed_mask, dimensions)

        if gpu is None:
            S = S.to(dtype=torch.float32)
            if rotation_matrix is not None:
                rotation_matrix = rotation_matrix.to(dtype=torch.float32)

        result = torch.matmul(S, rotation_matrix) if rotation_matrix is not None else S

    elif method == 'Decomp':
        #packed_mask = compressed_data['packed_mask']
        non_zero_elements = compressed_data['non_zero_elements']
        #dimensions = compressed_data['dimensions']
        avg_values = compressed_data['avg_values']
        packed_binary_matrix = compressed_data['packed_binary_matrix']
        og_shape_bin = compressed_data['og_shape_bin']

        #D = reconstruct_decomposition(packed_mask, non_zero_elements, dimensions, avg_values, packed_binary_matrix, og_shape_bin)
        D = reconstruct_decomposition(non_zero_elements, avg_values, packed_binary_matrix, og_shape_bin)

        if gpu is None:
            D = D.to(dtype=torch.float32)
            if rotation_matrix is not None:
                rotation_matrix = rotation_matrix.to(dtype=torch.float32)

        result = torch.matmul(D, rotation_matrix) if rotation_matrix is not None else D

    elif method == 'Spline':
        spline = compressed_data['spline']
        wt = compressed_data['wt']
        dimensions = compressed_data['dimensions']

        og_dtype = rotation_matrix.dtype
        D = reconstruct_spline(spline, wt, dimensions, og_dtype)

        if gpu is None:
            D = D.to(dtype=torch.float32)
            if rotation_matrix is not None:
                rotation_matrix = rotation_matrix.to(dtype=torch.float32)

        result = torch.matmul(D, rotation_matrix) if rotation_matrix is not None else D

    else:
        raise ValueError(f"Unknown method: {method}")

    decompression_time = time.perf_counter() - start_time

    return result, decompression_time

"""### **2.5 Custom Layer**"""

class CompressedLinear(nn.Module):
    def __init__(self, compressed_data, method, bias=None):
        super(CompressedLayer, self).__init__()
        self.compressed_data = compressed_data
        self.method = method
        self.bias = bias

        if method not in ['LRA', 'JPEG', 'DCT', 'EDCT']:
            self.out_features, self.in_features = compressed_data['dimensions']

    def __repr__(self):
        # Sobrescribir __repr__ para incluir las dimensiones y si tiene bias
        return f"CompressedLayer(in_features={self.in_features}, out_features={self.out_features}, bias={'True' if self.bias is not None else 'False'})"

    def forward(self, input_tensor):
        """
        Recibe un diccionario que contiene matrices comprimidas y genera una salida similar a una capa lineal.
        La descompresión de las matrices comprimidas se realiza dentro de este método.
        """
        output = None
        device = input_tensor.device


        if self.method not in ['LRA', 'JPEG', 'DCT', 'EDCT']:
            rotation_matrix = model.rotation_matrices.get(self.in_features, None).to(device)
            result = self.decompress_matrix(self.compressed_data, self.method, rotation_matrix.dtype)
            rotation_matrix = rotation_matrix.to(result.dtype)
            result = result.to(device)
            output = torch.matmul(torch.matmul(input_tensor, rotation_matrix.T), result.T)

        else:
            result = self.decompress_matrix(self.compressed_data, self.method)
            result = result.to(device)
            output = torch.matmul(input_tensor, result.T)


        # Realizar la multiplicación de matrices (simulando una capa lineal)
        if self.bias is not None:
            self.bias = self.bias.to(device)
            output = output + self.bias

        return output

    def decompress_matrix(self, compressed_data, method, og_dtype=None, num_segments=5):
        """
        Decompresses a single matrix from its compressed representation.

        Parameters:
            compressed_data (dict): The compressed representation of the matrix.
            method (str): The compression method used ('LRA', 'LocalTopK', 'Decomp', 'Spline', 'JPEG', 'DCT', 'EDCT').
            rotation_matrix (torch.Tensor, optional): The rotation matrix used during compression (if applicable).
            num_segments (int, optional): The number of segments for the 'Decomp' method.

        Returns:
            torch.Tensor: The decompressed matrix.
        """

        # Determine the device (MPS, CUDA, or CPU)
        if torch.backends.mps.is_available():
            device = "mps"
        elif torch.cuda.is_available():
            device = "cuda"
        else:
            device = "cpu"

        if method == 'LRA':
            US_r = compressed_data['US_r']
            Vt_r = compressed_data['Vt_r']

            if device == 'cpu':
                US_r = US_r.to(dtype=torch.float32)
                Vt_r = Vt_r.to(dtype=torch.float32)
            else:
                US_r = US_r.to(device)
                Vt_r = Vt_r.to(device)

            result = torch.matmul(US_r, Vt_r)

        elif method == 'LocalTopK':
            packed_mask = compressed_data['packed_mask']
            non_zero_elements = compressed_data['non_zero_elements']
            dimensions = compressed_data['dimensions']

            S = bitmap_to_matrix(non_zero_elements, packed_mask, dimensions)

            if device == 'cpu':
                S = S.to(dtype=torch.float32)
            else:
                S = S.to(device)

            result = S

        elif method == 'Decomp':
            packed_mask = compressed_data['packed_mask']
            non_zero_elements = compressed_data['non_zero_elements']
            dimensions = compressed_data['dimensions']
            avg_values = compressed_data['avg_values']
            packed_masks = compressed_data['packed_masks']

            D = reconstruct_decomposition(packed_mask, non_zero_elements, dimensions, avg_values, packed_masks)

            if device == 'cpu':
                D = D.to(dtype=torch.float32)
            else:
                D = D.to(device)

            result = D

        elif method == 'Spline':
            spline = compressed_data['spline']
            wt = compressed_data['wt']
            dimensions = compressed_data['dimensions']

            D = reconstruct_spline(spline, wt, dimensions, og_dtype)

            if device == 'cpu':
                D = D.to(dtype=torch.float32)
            else:
                D = D.to(device)

            result = D

        elif method == 'JPEG':
            huffman_encoded = compressed_data['huffman_encoded']
            huff_tree = compressed_data['huff_tree']
            shape = compressed_data['shape']
            Q = compressed_data['Q']

            result = decompress_jpeg(huffman_encoded, huff_tree, shape, Q)

        elif method == 'DCT':
            compressed = compressed_data['compressed']
            shape = compressed_data['shape']
            og_shape = compressed_data['og_shape']

            result = decompress_dct(compressed, shape, og_shape)

        elif method == 'EDCT':
            Ds = compressed_data['Ds']
            shape = compressed_data['shape']

            result = decompress_edct(Ds, shape)

        else:
            raise ValueError(f"Unknown method: {method}")

        return result

# Función para extraer bias si existe en el compressed_state_dict
def extract_bias(state_dict, layer_name):
    if layer_name + '.bias' in state_dict:
        return state_dict[layer_name + '.bias']
    else:
        return None  # Si no tiene bias, devolver None

# Función para extraer weight si existe en el compressed_state_dict
def extract_weight(state_dict, layer_name):
    weight_key = layer_name + '.weight'
    if weight_key in state_dict:
        weight = state_dict[weight_key]
        if isinstance(weight, dict):
            return weight
        else:
            return None
    else:
        return None  # Si no tiene weights, devolver None

# Función para reemplazar las capas lineales con las capas comprimidas
def replace_linear_layers_with_compressed(model, compressed_state_dict, method='Decomp'):
    # Asignar rotation_matrices al modelo como atributo global
    if 'rotation_matrices' in compressed_state_dict:
        model.rotation_matrices = compressed_state_dict['rotation_matrices']


    def traverse_and_replace(module, prefix=""):
        for name, submodule in module.named_children():
            full_name = prefix + name
            # Verificar si el nombre de la capa es una subcadena en alguna de las claves del compressed_state_dict
            for key in compressed_state_dict.keys():
                if full_name in key:
                    # Asegurarse de que el submódulo sea una capa lineal antes de reemplazar
                    if isinstance(submodule, nn.Linear):
                        compressed_data = extract_weight(compressed_state_dict, full_name)
                        bias = extract_bias(compressed_state_dict, full_name)
                        if compressed_data is not None:
                            compressed_layer = CompressedLayer(compressed_data, method, bias)
                            # Reemplazar la capa
                            setattr(module, name, compressed_layer)
                            #print(f"Layer {full_name} reemplazada con CompressedLayer.")
                    break  # Solo reemplazar una vez por cada capa lineal
            # Recursivamente revisar los submódulos
            traverse_and_replace(submodule, prefix=full_name + ".")

    # Iniciar el reemplazo con el modelo principal
    traverse_and_replace(model)
    return

def initialize_cache_and_workers():
    """
    Función para calcular dinámicamente el tamaño de la caché y el número de trabajadores,
    basada en los recursos disponibles del sistema.
    """
    # Obtener recursos del sistema
    total_ram = psutil.virtual_memory().total  # RAM total en bytes
    free_ram = psutil.virtual_memory().available  # RAM libre en bytes
    num_cores = multiprocessing.cpu_count()  # Número total de núcleos de CPU

    # Estimación de la cantidad de memoria que ocupa una matriz descomprimida (en bytes)
    # Este valor depende del tamaño de cada matriz. Asumimos un valor aproximado para cada matriz de 512 KB.
    matrix_size_estimate = 512 * 1024  # Aproximadamente 512 KB por matriz

    # Calcular cuánta memoria queda disponible para las matrices descomprimidas
    memory_for_matrices = free_ram * 0.8  # Asignamos un 80% de la memoria libre para las matrices

    # Calcular el máximo de matrices que podemos almacenar en caché sin exceder la memoria disponible
    max_matrices_in_cache = memory_for_matrices // (7 * matrix_size_estimate)

    # Ajustar para que sea el mayor múltiplo de 7
    max_cache_size = (max_matrices_in_cache // 7) * 7

    # Número de trabajadores (ajustado a la mitad de los núcleos de CPU)
    num_workers = max(2, min(8, num_cores // 2))

    # Caché global con lock
    cache = {}
    cache_lock = threading.Lock()

    # Devuelve los parámetros calculados
    return max_cache_size, num_workers, cache, cache_lock


def decompress_layer(layer):
    """Descomprime una capa y devuelve su resultado"""
    matrix = layer.decompress_matrix(layer.compressed_data).to(layer.bias.device)
    return layer, matrix

def batch_decompress(layers):
    """Descomprime un lote de capas en paralelo sin procesos adicionales"""
    decompressed_matrices = {}

    # Usar hilos en lugar de procesos
    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        results = executor.map(decompress_layer, layers)

    decompressed_matrices.update(dict(results))

    # Agregar a caché con lock
    with cache_lock:
        cache.update(decompressed_matrices)
        while len(cache) > max_cache_size:
            cache.pop(next(iter(cache)), None)  # Eliminar el menos reciente

class DecompLayer(nn.Module):
    def __init__(self, compressed_data, bias=None):
        super().__init__()
        self.compressed_data = compressed_data
        self.out_features, self.in_features = compressed_data['dimensions']
        self.bias = bias if bias is not None else torch.zeros(self.out_features)

    def __repr__(self):
        # Sobrescribir __repr__ para incluir las dimensiones y si tiene bias
        return f"DecompLayer(in_features={self.in_features}, out_features={self.out_features}, bias={'True' if self.bias is not None else 'False'})"


    def forward(self, input_tensor):
        device = input_tensor.device
        rotation_matrix = rotation_matrices.get(self.in_features, None).to(device).to(input_tensor.dtype)

        # Intentar obtener desde caché
        with cache_lock:
            result = cache.get(self, None)

        if result is None:
            result = self.decompress_matrix(self.compressed_data).to(device).to(input_tensor.dtype)
            with cache_lock:
                cache[self] = result

        output = torch.bmm(torch.bmm(input_tensor, rotation_matrix.T.unsqueeze(0)), result.T.unsqueeze(0)) + self.bias
        return output.to(input_tensor.dtype)

    def decompress_matrix(self, compressed_data):
        """Descomprime una matriz desde su representación comprimida."""
        return reconstruct_decomposition(
            compressed_data['non_zero_elements'],
            compressed_data['avg_values'],
            compressed_data['packed_binary_matrix'],
            compressed_data['og_shape_bin']
        )

# Función para reemplazar las capas lineales con las capas comprimidas
def replace_linear_layers_with_decomp(model, compressed_state_dict, method, rotation_matrices=None):
    # Asignar rotation_matrices al modelo como atributo global
    if rotation_matrices is not None:
        model.rotation_matrices = rotation_matrices

    def traverse_and_replace_decomp(module, prefix=""):
        for name, submodule in module.named_children():
            full_name = prefix + name
            # Verificar si el nombre de la capa es una subcadena en alguna de las claves del compressed_state_dict
            for key in compressed_state_dict.keys():
                if full_name in key:
                    # Asegurarse de que el submódulo sea una capa lineal antes de reemplazar
                    if isinstance(submodule, nn.Linear):
                        compressed_data = extract_weight(compressed_state_dict, full_name)
                        bias = extract_bias(compressed_state_dict, full_name)
                        if compressed_data is not None:
                            compressed_layer = DecompLayer(compressed_data, bias)
                            # Reemplazar la capa
                            setattr(module, name, compressed_layer)
                            #print(f"Layer {full_name} reemplazada con CompressedLayer.")
                    break  # Solo reemplazar una vez por cada capa lineal
            # Recursivamente revisar los submódulos
            traverse_and_replace_decomp(submodule, prefix=full_name + ".")

    # Iniciar el reemplazo con el modelo principal
    traverse_and_replace_decomp(model)

"""### **2.6 Save and Load Compressed Model**"""

def save_compressed_model(model, compressed_state_dict, path):
    # Guardar los pesos del modelo junto con el 'rotation_matrices'
    model.load_state_dict(compressed_state_dict, strict=False)  # Cargar el compressed_state_dict
    if 'rotation_matrices' in compressed_state_dict:
        model.rotation_matrices = compressed_state_dict['rotation_matrices']  # Restaurar rotation_matrices

    # Guardar el modelo completo
    torch.save(model, path)  # Guardar el modelo con los pesos y rotation_matrices


def load_compressed_model(path):
    # Cargar el modelo completo desde el archivo
    model = torch.load(path, weights_only=False)

    # Verificar si 'rotation_matrices' está presente, en caso de que quieras acceder a ella
    if hasattr(model, 'rotation_matrices'):
        rotation_matrices = model.rotation_matrices

        print("rotation_matrices cargadas correctamente")
    else:
        print("No se encontró rotation_matrices")

    return model, rotation_matrices

"""### **2.7 Test Model**"""

def test_model_qa(tokenizer, compressed_model, context, questions):
    """
    Función para realizar predicciones sobre un conjunto de preguntas y un contexto dado.

    Args:
    - tokenizer: Tokenizador del modelo.
    - compressed_model: Modelo comprimido para realizar la inferencia.
    - context: Texto de contexto para las preguntas.
    - questions: Lista de preguntas a responder.

    Prints:
    - La pregunta y la respuesta para cada una de las preguntas.
    """
    for question in questions:
      # Asegurar que haya un token de padding
        if tokenizer.pad_token is None:
            tokenizer.add_special_tokens({'pad_token': tokenizer.eos_token})  # Utilizar el token de fin de secuencia como padding

        # Tokenizar la pregunta y el contexto
        inputs = tokenizer(question, context, return_tensors="pt", padding=True, truncation=True, max_length=512)

        # Record the start time for inference
        start_time = time.time()

        # Realizar la predicción
        outputs = compressed_model(**inputs)

        # Obtener la posición de inicio y fin de la respuesta
        start_index = outputs.start_logits.argmax(dim=1).item()
        end_index = outputs.end_logits.argmax(dim=1).item()

        # Extraer y decodificar la respuesta
        tokens = inputs["input_ids"][0][start_index : end_index + 1]
        answer = tokenizer.decode(tokens, skip_special_tokens=True)

        # Record the end time for inference
        end_time = time.time()

        # Calculate the inference time
        inference_time = end_time - start_time

        # Mostrar la pregunta y la respuesta
        print(f"Question: {question}")
        print(f"Answer: {answer}")
        print(f"Inference time: {inference_time:.4f} seconds\n")

def test_model_generation(tokenizer, compressed_model, queries):
    """
    Function to make predictions on a set of queries using a text generation model.

    Args:
    - tokenizer: Tokenizer for the model.
    - compressed_model: Compressed model for inference.
    - queries: List of queries to answer.

    Prints:
    - The query and the generated response for each of the queries.
    - The inference time for each query.
    """
    # Ensure there is a padding token
    if tokenizer.pad_token is None:
        tokenizer.add_special_tokens({'pad_token': tokenizer.eos_token})  # Use the EOS token as padding

    for query in queries:
        # In this case, the query is just the prompt and context is empty or not used
        inputs = tokenizer(query, return_tensors="pt", padding=True, truncation=True, max_length=512)

        # Mover tensores a la misma GPU donde está el modelo
        inputs = {k: v.to(compressed_model.device) for k, v in inputs.items()}

        # Ensure the attention mask is included
        attention_mask = inputs.get("attention_mask", None)

        # Record the start time for inference
        start_time = time.time()

        # Perform the generative prediction
        outputs = compressed_model.generate(
            inputs["input_ids"],
            attention_mask=attention_mask,  # Pass attention if available
            max_length=25,  # Maximum length of the generated response
            num_return_sequences=1,  # Number of sequences to generate
            no_repeat_ngram_size=2,  # Avoid n-gram repetition
            temperature=0.1,  # Controls the creativity of the responses
            top_k=50,  # Controls the variety of the responses
            #top_p=0.95,  # Controls the cumulative probability
            pad_token_id=tokenizer.pad_token_id,  # Ensure the padding token is used
            eos_token_id=tokenizer.eos_token_id,  # Ensure the EOS token is used
        )

        # Decode the generated response
        generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

        # Record the end time for inference
        end_time = time.time()

        # Calculate the inference time
        inference_time = end_time - start_time

        # Print the query, generated response, and inference time
        print(f"Query: {query}")
        print(f"Generated response: {generated_text}")
        print(f"Inference time: {inference_time:.4f} seconds\n")

"""### **2.8 Approximate Model Matrices**"""

def approximate_model_matrices(model, weights, method, rotation_matrices=None, num_bits=4):

    if (method not in ['LRA', 'JPEG', 'DCT', 'EDCT']) and (rotation_matrices is None):
        rotation_matrices = compute_rotation_matrices_of_weights(weights)

    modified_state_dict = {}

    for key, weight in weights.items():
        og_dtype = weight.dtype

        # Verificar si el tensor pertenece a una capa Linear
        is_linear_layer = any(key.startswith(name) and isinstance(layer, torch.nn.Linear)
                              for name, layer in model.named_modules())

        # Solo comprimir si es una matriz 2D, pertenece a una capa Linear y tiene "layer" en el nombre
        if weight.ndimension() == 2 and "layer" in key and is_linear_layer:
            matrix_start_time = time.perf_counter()

            matrix = weight

            num_parameters = int(matrix.shape[0] * matrix.shape[1] * 0.8)

            if method == 'LRA':
                US_r, Vt_r = low_rank_approximation(matrix, num_parameters)
                result = torch.matmul(US_r, Vt_r)
                modified_state_dict[key] = result


            elif method == 'JPEG':
                huffman_encoded, huff_tree, shape, Q = compress_jpeg(matrix)
                result = decompress_jpeg(huffman_encoded, huff_tree, shape, Q)
                modified_state_dict[key] = result

            elif method == 'DCT':
                non_zero_elements, packed_mask, bitmap_shape, shape, og_shape = compress_dct(matrix, og_dtype=matrix.dtype)
                result = decompress_dct(non_zero_elements, packed_mask, bitmap_shape, shape, og_shape)
                result = result.to(matrix.dtype)
                modified_state_dict[key] = result

            elif method == 'EDCT':
                Ds, shape = compress_edct(matrix,og_dtype=matrix.dtype)
                result = decompress_edct(Ds, shape)
                modified_state_dict[key] = result

            elif method == 'LocalTopK':
                Q = rotation_matrices[matrix.shape[1]].to(dtype=matrix.dtype)
                D = torch.matmul(matrix, Q.T)
                S = local_topk(D, num_parameters)


                result = torch.matmul(S, Q)
                modified_state_dict[key] = result

            elif method == 'Decomp':
                Q = rotation_matrices[matrix.shape[1]].to(dtype=matrix.dtype)
                D = torch.matmul(matrix, Q.T)

                dimensions = D.shape
                non_zero_elements, avg_values, packed_binary_matrix, og_shape_bin = decomposition(D, num_bits)
                D_new = reconstruct_decomposition(non_zero_elements, avg_values, packed_binary_matrix, og_shape_bin)

                result = torch.matmul(D_new.to(Q.dtype), Q)
                modified_state_dict[key] = result

            elif method == 'Spline':
                Q = rotation_matrices[matrix.shape[1]].to(dtype=matrix.dtype)
                D = torch.matmul(matrix, Q.T)
                spline, wt, dimensions = compute_spline(D)

                og_dtype = matrix.dtype
                D = reconstruct_spline(spline, wt, dimensions, og_dtype)

                result = torch.matmul(D_new, Q)
                modified_state_dict[key] = result
        else:
            # Para tensores que no cumplen los requisitos, se almacenan sin cambios
            modified_state_dict[key] = weight

    # Agregar rotation_matrices al diccionario final
    modified_state_dict['rotation_matrices'] = rotation_matrices

    return modified_state_dict

def replace_linear_layers_with_approx(model, modified_state_dict):
    # Asignar rotation_matrices al modelo si están presentes
    if 'rotation_matrices' in modified_state_dict:
        model.rotation_matrices = modified_state_dict['rotation_matrices']

    def traverse_and_replace_approx(module, prefix=""):
        for name, submodule in module.named_children():
            full_name = prefix + name

            # Si el submódulo es una capa Linear, intentamos reemplazar sus pesos
            if isinstance(submodule, nn.Linear):
                weight_key = full_name + '.weight'
                bias_key = full_name + '.bias'

                if weight_key in modified_state_dict:
                    # Reemplazar los pesos de la capa
                    approx_weight = modified_state_dict[weight_key]
                    with torch.no_grad():
                        submodule.weight.copy_(approx_weight)

                if submodule.bias is not None and bias_key in modified_state_dict:
                    approx_bias = modified_state_dict[bias_key]
                    with torch.no_grad():
                        submodule.bias.copy_(approx_bias)

            # Recursivamente continuar con los submódulos
            traverse_and_replace_approx(submodule, prefix=full_name + ".")

    # Iniciar el proceso desde el modelo principal
    traverse_and_replace_approx(model)
    return

##################################### FLAG

print("Program finished")
input("Press Enter to exit...")